[Variables]

skinSize=(#SCREENAREAHEIGHT#*0.5)
lastSetWidth=432

Player=Spotify
alignRight=0

activePlugin=NowPlaying

topTextWidth=514
bottomTextWidth=105

; 0 = MUSIC, 2 = WEBNOWPLAYING
MusicSwitch=0
playerController=Title0
currentlySetName=Spotify (NowPlaying)
currentlySetPlayer=WMP

adaptiveHideActive=1

stowAway=0
stowAwayName=NULL

topText=mTitle
bottomText=mArtist

disableScroll=0

removeExtraFromText=1

thinFont=Metropolis Extra Light
thickFont=Metropolis Medium
controlsFont=Metropolis Medium

mediaTextPositionHor=0
mediaTextAlignment=LeftBottom
mediaTextAlignmentPure=Left
interfaceTextAlignment=Right
nowTextPositionHor=79.92
hairlinePositionHor=92.88
topTextPositionHor=106.92
playCtrlPositionHor=43.2
settingsTextPositionHor=49.68
indicatorPositionHor=30.24
indicatorPositionHorPure=17.28
conflictIndicatorPositionHor=12.96
conflictIndicatorPositionHorPure=34.56
